version = 3
final_space = true
console_title_template = '{{ .Shell }} in {{ .Folder }}'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'path'
    style = 'plain'
    background = 'transparent'
    foreground = 'p:blue'
    template = '{{ .Path }}'

    [blocks.segments.properties]
      style = 'full'

    [[blocks.segments]]
      type = 'git'
      style = 'plain'
      foreground = 'p:purple'
      background = 'transparent'
      template = ' <p:grey>{{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }}* {{ .Working.String }}{{ end }}</> <cyan>{{ if gt .Behind 0}}⇣{{ end }}{{ if gt .Ahead 0}}⇡</>{{ end }}'

      [blocks.segments.properties]
        branch_icon = ''
	commit_icon = '@'
	fetch_status = true

[[blocks]]
  type = 'rprompt'
  overflow = 'hidden'

  [[blocks.segments]]
    type = 'executiontime'
    style = 'plain'
    foreground = 'p:yellow'
    background = 'transparent'
    template = '{{ div .Ms 1000 }}s'

    [blocks.segments.properties]
      threshold = 5000
      style = ''

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground_templates = [
      "{{if gt .Code 0}}p:red{{end}}",
      "{{if eq .Code 0}}p:purple{{end}}",
    ]
    background = 'transparent'
    template = '❱'

[transient_prompt]
  foreground_templates = [
    "{{if gt .Code 0}}p:red{{end}}",
    "{{if eq .Code 0}}p:purple{{end}}",
  ]
  background = 'transparent'
  template = '❱ '

[secondary_prompt]
  foreground = 'p:blue'
  background = 'transparent'
  template = '❱❱ '

[palette]
  grey = '#9E9E9E'
  blue = '#A2A2FA'
  purple = '#926AB8'
  red = '#FF6D66'
  yellow = '#FFC85A'
