general.import = [
  "~/.config/alacritty/themes/themes/tokyo_night.toml"
]

[env]
  TERM = "xterm-256color"

[window]
  padding.x = 10
  padding.y = 20

  dynamic_padding = true

  decorations = "Transparent"

  opacity = 0.7
  blur = true

  option_as_alt = "Both"
  title = "Alacritty"

[font]
  normal.family = "MesloLGL Nerd Font"

  size = 16
  offset = { x = 1, y = 3}
